# Generated by Django 2.0.5 on 2018-08-01 12:47

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product/2238217906.jpg', upload_to=product.models.upload_image_path),
        ),
    ]
